name: CD-NuGet

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Pack
      run: |
        dotnet nuget update source PackSite --configfile ./src/NuGet.config -u ${{ secrets.GPR_OWNER }} -p ${{secrets.GPR_TOKEN }} --store-password-in-clear-text
        dotnet pack src/PackSite.Library.Pipelining.sln --configuration Release

    - name: Deploy
      run: |
        dotnet nuget push src/PackSite.Library.Pipelining/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push src/PackSite.Library.Pipelining.Abstractions/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push src/PackSite.Library.Pipelining.Configuration/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
