name: CI

on:
  push:
    branches:
      - main
      - develop
    tags-ignore:
      - '*'

jobs:
  build:
    name: 'Build & test ''${{ github.repository }}'''
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Ensure PackSite NuGet Source Exists & Update
        run: |
          find . -name NuGet.config | while read configfile; do
            if [[ -f "$configfile" ]]; then
              if grep -q '<add key="PackSite"' "$configfile"; then
                echo "Updating NuGet source 'PackSite' in '$configfile'"
                dotnet nuget update source PackSite --configfile "$configfile" -u "${{ secrets.GPR_OWNER }}" -p "${{ secrets.GPR_TOKEN }}" --store-password-in-clear-text
              else
                echo "Adding NuGet source 'PackSite' to '$configfile'"
                dotnet nuget add source "https://nuget.pkg.github.com/${{ secrets.GPR_OWNER }}/index.json" \
                  --name PackSite \
                  --configfile "$configfile" \
                  --username "${{ secrets.GPR_OWNER }}" \
                  --password "${{ secrets.GPR_TOKEN }}" --store-password-in-clear-text
              fi
            else
              echo "No NuGet.config file found."
            fi
          done

      - name: Build & Test
        run: |
          find . -name "*.sln*" | while read slnfile; do
            if [[ -f "$slnfile" ]]; then
              echo "Building and testing $slnfile"
              dotnet test "$slnfile" --configuration Release
            else
              echo "No solution file found."
            fi
          done
